//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinuousPrimate.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContinuousPrimate.Test.Words", typeof(Words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michael
        ///Christopher
        ///Jessica
        ///Matthew
        ///Ashley
        ///Jennifer
        ///Joshua
        ///Amanda
        ///Daniel
        ///David
        ///James
        ///Robert
        ///John
        ///Joseph
        ///Andrew
        ///Ryan
        ///Brandon
        ///Jason
        ///Justin
        ///Sarah
        ///William
        ///Jonathan
        ///Stephanie
        ///Brian
        ///Nicole
        ///Nicholas
        ///Anthony
        ///Heather
        ///Eric
        ///Elizabeth
        ///Adam
        ///Megan
        ///Melissa
        ///Kevin
        ///Steven
        ///Thomas
        ///Timothy
        ///Christina
        ///Kyle
        ///Rachel
        ///Laura
        ///Lauren
        ///Amber
        ///Brittany
        ///Danielle
        ///Richard
        ///Kimberly
        ///Jeffrey
        ///Amy
        ///Crystal
        ///Michelle
        ///Tiffany
        ///Jeremy
        ///Benjamin
        ///Mark
        ///Emily
        ///Aaron
        ///Charles
        ///Rebecca
        ///Jacob
        ///Stephen
        ///Patri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Johnson
        ///Williams
        ///Brown
        ///Jones
        ///Garcia
        ///Miller
        ///Davis
        ///Rodriguez
        ///Martinez
        ///Hernandez
        ///Lopez
        ///Gonzalez
        ///Wilson
        ///Anderson
        ///Thomas
        ///Taylor
        ///Moore
        ///Jackson
        ///Martin
        ///Lee
        ///Perez
        ///Thompson
        ///White
        ///Harris
        ///Sanchez
        ///Clark
        ///Ramirez
        ///Lewis
        ///Robinson
        ///Walker
        ///Young
        ///Allen
        ///King
        ///Wright
        ///Scott
        ///Torres
        ///Nguyen
        ///Hill
        ///Flores
        ///Green
        ///Adams
        ///Nelson
        ///Baker
        ///Hall
        ///Rivera
        ///Campbell
        ///Mitchell
        ///Carter
        ///Roberts
        ///Gomez
        ///Phillips
        ///Evans
        ///Turner
        ///Diaz
        ///Parker
        ///Cruz
        ///Edwards
        ///Collins
        ///Reyes
        ///Stewart
        ///Morris
        ///Morales
        ///Murphy        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
    }
}
