//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinuousPrimate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wordlist {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wordlist() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContinuousPrimate.Wordlist", typeof(Wordlist).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to able
        ///unable
        ///abaxial
        ///dorsal
        ///adaxial
        ///ventral
        ///acroscopic
        ///basiscopic
        ///abducent
        ///abducting
        ///adducent
        ///adductive
        ///adducting
        ///nascent
        ///emergent
        ///emerging
        ///dissilient
        ///parturient
        ///dying
        ///moribund
        ///last
        ///abridged
        ///cut
        ///shortened
        ///potted
        ///unabridged
        ///uncut
        ///absolute
        ///direct
        ///implicit
        ///unquestioning
        ///infinite
        ///living
        ///relative
        ///comparative
        ///relational
        ///absorbent
        ///absorptive
        ///absorbefacient
        ///sorbefacient
        ///assimilating
        ///assimilative
        ///assimilatory
        ///hygroscopic
        ///receptive
        ///spongy
        ///spongelike
        ///thirsty
        ///nonabsorbent        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michael
        ///Christopher
        ///Jessica
        ///Matthew
        ///Ashley
        ///Jennifer
        ///Joshua
        ///Amanda
        ///Daniel
        ///David
        ///James
        ///Robert
        ///John
        ///Joseph
        ///Andrew
        ///Ryan
        ///Brandon
        ///Jason
        ///Justin
        ///Sarah
        ///William
        ///Jonathan
        ///Stephanie
        ///Brian
        ///Nicole
        ///Nicholas
        ///Anthony
        ///Heather
        ///Eric
        ///Elizabeth
        ///Adam
        ///Megan
        ///Melissa
        ///Kevin
        ///Steven
        ///Thomas
        ///Timothy
        ///Christina
        ///Kyle
        ///Rachel
        ///Laura
        ///Lauren
        ///Amber
        ///Brittany
        ///Danielle
        ///Richard
        ///Kimberly
        ///Jeffrey
        ///Amy
        ///Crystal
        ///Michelle
        ///Tiffany
        ///Jeremy
        ///Benjamin
        ///Mark
        ///Emily
        ///Aaron
        ///Charles
        ///Rebecca
        ///Jacob
        ///Stephen
        ///Patri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity
        ///abstraction
        ///thing
        ///object
        ///whole
        ///unit
        ///congener
        ///organism
        ///being
        ///benthos
        ///dwarf
        ///heterotroph
        ///parent
        ///life
        ///biont
        ///cell
        ///cause
        ///person
        ///individual
        ///someone
        ///somebody
        ///mortal
        ///soul
        ///animal
        ///beast
        ///brute
        ///creature
        ///fauna
        ///plant
        ///flora
        ///native
        ///substance
        ///matter
        ///food
        ///nutrient
        ///artifact
        ///artefact
        ///article
        ///cognition
        ///knowledge
        ///noesis
        ///motivation
        ///motive
        ///need
        ///attribute
        ///state
        ///feeling
        ///location
        ///shape
        ///form
        ///time
        ///space
        ///infinite
        ///event
        ///process
        ///act
        ///deed
        ///group
        ///grouping
        ///relation
        ///possession
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
    }
}
